version: '2'
services:
  kibana:
    build: kb-docker/.
    expose:
      - "5601"
    ports:
     - "5601:5601"
    environment:
      SERVER_HOST: "0.0.0.0"
  elasticsearch:
    build: es-docker/.
    ports:
     - "9200:9200"
    expose:
      - "9200"
    environment:
      SERVER_NAME: "elasticsearch"
      discovery.type: "single-node" 
    volumes:
      - es-data:/usr/share/elasticsearch/data

volumes:
  es-data:
    driver: local
